### ISSUE TITLE
how to change my username.

### ISSUE THREAD

**Issue by hadeszeusposeidon** [preccrep/hexo-theme-solid#1]
I used blog but can you tell me how to change the username in the main page please. I can't find the thing that changes the username in the comfig.yml. Thanks very much, I'm always online. Last question, where are you from?

**Comment by preccrep** [comment]
Change the username by editing the `author` term  in the `_config.yml` file in your root directory.
I'm from China.

**Comment by 1900710128** [comment]
为啥更换头像显示不出

**Comment by preccrep** [comment]
> 为啥更换头像显示不出

清一下浏览器缓存，多刷新几次

**Comment by 1900710128** [comment]
谢谢你可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "preccrep/hexo-theme-jelly"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月7日(星期二) 晚上6:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [preccrep/hexo-theme-jelly] how to change my username. (#1)





  
为啥更换头像显示不出
  
清一下浏览器缓存，多刷新几次
